version: 0.0
os: linux
files:
  - source: ./
    destination: /new_chatapp
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/django.sh
      timeout: 600
      runas: root
